In [10]:
import pandas as pd
# Test Combining
df_train = pd.read_csv('../data/processed_metadata_train.csv')
df_test = pd.read_csv('../data/processed_metadata_test.csv')

In [11]:
df_train

,image_id,identity,path,bbox,keypoints,original_split,processed_path
0,d914a6c6d93c8df0,0,atrw_reid_train/train/004759.jpg,NaN,[ 194 233 2 204 85 2 59 362 2 ...,train,./data/segmented_dataset_train/0
1,8f4576ad85410442,0,atrw_reid_train/train/004648.jpg,NaN,[ 0 0 0 1207 378 2 1245 448 2 ...,train,./data/segmented_dataset_train/0
2,375c71349b295fbe,0,atrw_reid_train/train/001703.jpg,NaN,[ 200 283 2 184 121 2 29 402 2 ...,train,./data/segmented_dataset_train/0
3,2288f691b58edeca,0,atrw_reid_train/train/002558.jpg,NaN,[ 215 243 2 242 85 2 98 348 2 ...,train,./data/segmented_dataset_train/0
4,abec16f483abb4f1,0,atrw_reid_train/train/003997.jpg,NaN,[ 232 333 2 159 162 2 36 477 2 ...,train,./data/segmented_dataset_train/0
...,...,...,...,...,...,...,...
2923,876e1c59023b1a0e,274,atrw_reid_train/train/005152.jpg,NaN,[ 0 0 0 585 103 2 0 0 0 468 175 ...,train,./data/segmented_dataset_train/274
2924,ddeebdeefdb7e7e7,274,atrw_reid_train/train/002411.jpg,NaN,[462 96 2 456 105 2 487 197 2 363 178 ...,train,./data/segmented_dataset_train/274
2925,f80ff32e08a25270,274,atrw_reid_train/train/002086.jpg,NaN,[572 73 2 576 91 2 606 180 2 403 145 ...,train,./data/segmented_dataset_train/274
2926,df877f3865752637,274,atrw_reid_train/train/000533.jpg,NaN,[ 0 0 0 393 82 2 403 162 2 225 152 ...,train,./data/segmented_dataset_train/274
2927,061412e4a03c02f9,274,atrw_reid_train/train/000896.jpg,NaN,[ 0 0 0 428 99 2 457 180 2 274 153 ...,train,./data/segmented_dataset_train/274

In [12]:
df_test

,image_id,identity,path,bbox,keypoints,original_split,processed_path
0,690bb330e5e7e3e0,0,atrw_reid_train/train/003791.jpg,NaN,[ 54 119 2 158 34 2 51 211 2 ...,train,./data/segmented_dataset_test/0
1,1cfead9959b76ce4,0,atrw_reid_train/train/003107.jpg,NaN,[ 140 239 2 194 103 2 52 349 2 ...,train,./data/segmented_dataset_test/0
2,1e4d36177d71bbb3,1,atrw_reid_train/train/001983.jpg,NaN,[820 150 2 581 144 2 735 373 2 475 435 ...,train,./data/segmented_dataset_test/1
3,f197002b9a0853ec,1,atrw_reid_train/train/001151.jpg,NaN,[812 104 2 833 143 2 910 259 2 690 375 ...,train,./data/segmented_dataset_test/1
4,3fe94a002317b5f9,3,atrw_reid_train/train/000316.jpg,NaN,[130 46 2 0 0 0 0 0 0 0 0 ...,train,./data/segmented_dataset_test/3
...,...,...,...,...,...,...,...
718,331cc28f8747a032,273,atrw_reid_train/train/004191.jpg,NaN,[ 16 7 2 0 0 0 0 0 0 190 173 ...,train,./data/segmented_dataset_test/273
719,d305281faf947ca7,273,atrw_reid_train/train/001870.jpg,NaN,[ 16 36 2 0 0 0 0 0 0 200 189 ...,train,./data/segmented_dataset_test/273
720,6e0721b2c6977135,274,atrw_reid_train/train/000783.jpg,NaN,[360 74 2 383 95 2 375 169 2 204 154 ...,train,./data/segmented_dataset_test/274
721,6e0e24295e8a8628,274,atrw_reid_train/train/002836.jpg,NaN,[374 154 2 341 167 2 425 257 2 243 318 ...,train,./data/segmented_dataset_test/274
722,70afbf2259b4449d,274,atrw_reid_train/train/004457.jpg,NaN,[557 78 2 548 89 2 580 179 2 378 151 ...,train,./data/segmented_dataset_test/274

In [14]:
df = pd.concat([df_train, df_test], ignore_index = True)

In [15]:
df

,image_id,identity,path,bbox,keypoints,original_split,processed_path
0,d914a6c6d93c8df0,0,atrw_reid_train/train/004759.jpg,NaN,[ 194 233 2 204 85 2 59 362 2 ...,train,./data/segmented_dataset_train/0
1,8f4576ad85410442,0,atrw_reid_train/train/004648.jpg,NaN,[ 0 0 0 1207 378 2 1245 448 2 ...,train,./data/segmented_dataset_train/0
2,375c71349b295fbe,0,atrw_reid_train/train/001703.jpg,NaN,[ 200 283 2 184 121 2 29 402 2 ...,train,./data/segmented_dataset_train/0
3,2288f691b58edeca,0,atrw_reid_train/train/002558.jpg,NaN,[ 215 243 2 242 85 2 98 348 2 ...,train,./data/segmented_dataset_train/0
4,abec16f483abb4f1,0,atrw_reid_train/train/003997.jpg,NaN,[ 232 333 2 159 162 2 36 477 2 ...,train,./data/segmented_dataset_train/0
...,...,...,...,...,...,...,...
3646,331cc28f8747a032,273,atrw_reid_train/train/004191.jpg,NaN,[ 16 7 2 0 0 0 0 0 0 190 173 ...,train,./data/segmented_dataset_test/273
3647,d305281faf947ca7,273,atrw_reid_train/train/001870.jpg,NaN,[ 16 36 2 0 0 0 0 0 0 200 189 ...,train,./data/segmented_dataset_test/273
3648,6e0721b2c6977135,274,atrw_reid_train/train/000783.jpg,NaN,[360 74 2 383 95 2 375 169 2 204 154 ...,train,./data/segmented_dataset_test/274
3649,6e0e24295e8a8628,274,atrw_reid_train/train/002836.jpg,NaN,[374 154 2 341 167 2 425 257 2 243 318 ...,train,./data/segmented_dataset_test/274
3650,70afbf2259b4449d,274,atrw_reid_train/train/004457.jpg,NaN,[557 78 2 548 89 2 580 179 2 378 151 ...,train,./data/segmented_dataset_test/274

In [16]:
import pickle

path = '../data/db/fisher_vectors.pkl'
with open(path, 'rb') as file:
    data = pickle.load(file)

data

{'0004d0b59e19461f': array([-0.03328189,  0.01284098,  0.05835569,  0.0470312 , -0.07058137,
         0.0301666 ,  0.01820014,  0.03295981,  0.04253956, -0.06094044,
         0.01530127, -0.04129628, -0.04815121, -0.01716179, -0.04278894,
         0.02369652, -0.05150141,  0.05857952, -0.0082859 , -0.01286778,
         0.03887304, -0.02549339, -0.05879996, -0.0476239 , -0.04320755,
         0.04445308,  0.05257537,  0.05657399,  0.01489663,  0.0404902 ,
         0.02720805,  0.04151414,  0.05129088,  0.04883378,  0.02243563,
         0.05054209,  0.01178208,  0.01463844, -0.05281115, -0.04051438,
         0.06256182, -0.01758222,  0.0506338 , -0.00270695, -0.0504012 ,
         0.03915659, -0.03018748, -0.05065836, -0.03311222, -0.05709512,
        -0.03298701,  0.06684225, -0.02479512, -0.03181572, -0.00586316,
        -0.01760362, -0.0242648 , -0.0045354 ,  0.03093198,  0.03553616,
        -0.03932221, -0.05124358,  0.03664059,  0.01610286, -0.02782295,
         0.05549128, -0.00881863,  0.0188053 ,  0.02895777,  0.04477464,
         0.05196394,  0.05774261,  0.02411785,  0.02092923, -0.01547464,
        -0.03200427,  0.05265652, -0.02353627,  0.01122768,  0.03456467,
        -0.05132949, -0.03216563,  0.04195095, -0.02320215,  0.03941149,
         0.03576956, -0.01444488,  0.05808659,  0.04845896,  0.01104036,
         0.02140271,  0.02898343, -0.00535575, -0.05773632,  0.02787673,
         0.02445034,  0.03821072, -0.01382083, -0.01257391,  0.03048774,
        -0.02467157, -0.01632114,  0.01636023,  0.03118291,  0.03635721,
        -0.03250501,  0.01510513, -0.03554961, -0.02140611,  0.0061588 ,
        -0.04520329,  0.05282313, -0.01254491, -0.03415197, -0.02406437,
        -0.01592731, -0.02579413,  0.02755998,  0.02125973,  0.0674074 ,
        -0.04058337,  0.02404368, -0.01866034,  0.08979784, -0.0501905 ,
         0.06157902,  0.10078019,  0.03206955, -0.07627741, -0.08988311,
        -0.08248469,  0.04977538,  0.09261036, -0.07691134,  0.04687919,
        -0.04651817,  0.05340874, -0.08130649, -0.04076108,  0.06226866,
         0.10553739,  0.03365824,  0.0286912 , -0.05378685,  0.07938694,
        -0.07459296, -0.04436145, -0.07976002,  0.07340842,  0.04702782,
         0.08393539, -0.0497738 ,  0.0459133 ,  0.04939575,  0.09220468,
         0.04173084,  0.03988719,  0.03771992,  0.1002128 , -0.03220708,
         0.02448026,  0.01767447, -0.06645873,  0.10448836, -0.071201  ,
         0.08111896, -0.07187372,  0.01359381,  0.06627576, -0.04262358,
         0.02783555, -0.03701717, -0.07055669, -0.07475091,  0.08494719,
         0.01173177, -0.07202639, -0.05507298, -0.0567398 ,  0.04978592,
        -0.03310913, -0.01661258,  0.08102161, -0.02575194,  0.05752881,
        -0.04746974, -0.06233779, -0.03943935,  0.04737306, -0.08452353,
        -0.07248058, -0.02808132,  0.06106595,  0.09106163,  0.09309636,
         0.02745637,  0.07179958, -0.02415005, -0.05188312,  0.05977131,
         0.04306202,  0.01490165,  0.04234441, -0.07673282,  0.07028664,
        -0.0624622 ,  0.05505015,  0.00847161,  0.06860571, -0.06889307,
         0.09874988,  0.04942979,  0.08839582, -0.06158344, -0.0642618 ,
         0.04801914, -0.10104293,  0.06167586,  0.03394674,  0.00987305,
        -0.06695136,  0.07009666,  0.05103871, -0.02547714,  0.0633277 ,
        -0.02875263,  0.05974978,  0.06289696,  0.10080978, -0.06387108,
         0.01657885, -0.09183492, -0.03556444, -0.08696897,  0.07850659,
         0.10158286, -0.07006017, -0.06894115,  0.0542761 , -0.03188818,
         0.06201685,  0.02992231,  0.09402698, -0.07523808,  0.05391745,
        -0.01970202, -0.05160706,  0.03624357,  0.0193722 , -0.02635645,
         0.02609528, -0.03931934, -0.03461852, -0.01324341,  0.01552472,
         0.02649289, -0.02023686, -0.02001339, -0.03410155, -0.04398781,
         0.01805501, -0.03516424,  0.04228527, -0.00960883, -0.03737504,
         0.01579184, -0.03554033, -0.02837349,  0.02788801,  0.0119339 ,
        -0.00589146, -0.01903799,  0.03853228, -0.01090859, -0.02877857,
        -0.03625592, -0.00809106, -0.0451592 ,  0.03237149,  0.0201111 ,
         0.00927484, -0.03364018, -0.01916513, -0.04195519, -0.03363007,
         0.00613671,  0.01145496, -0.02710267,  0.02600632, -0.01600451,
        -0.03760539,  0.00714333, -0.03387438, -0.02118277,  0.0194684 ,
        -0.03745034, -0.03404306,  0.01324912, -0.03126854,  0.01636011,
         0.03482113, -0.04194229, -0.0079689 , -0.03291743, -0.03271861,
        -0.03362361,  0.02724128,  0.0442485 ,  0.00451788,  0.01617618,
        -0.03051109,  0.00836041,  0.02006395, -0.01040528, -0.02806773,
        -0.03737401,  0.01807539,  0.02292888, -0.00912017,  0.01883395,
        -0.01314454, -0.02074941,  0.0062505 , -0.02404498, -0.0182788 ,
        -0.02832207, -0.03613103,  0.03951041, -0.03337527, -0.02204499,
        -0.02149019, -0.02508349, -0.03471014, -0.02275622,  0.02297422,
        -0.03584899, -0.03379671, -0.03941611, -0.02723969,  0.01815755,
        -0.03587217, -0.04135136, -0.0417248 , -0.01950118, -0.03095907,
        -0.04435737, -0.02003267, -0.02801191, -0.03543784, -0.02585548,
        -0.04106624, -0.02698551, -0.03400797, -0.03422797, -0.02624638,
        -0.03419899, -0.02323689, -0.03837795, -0.01016559, -0.00829302,
        -0.02808657, -0.03628479, -0.03037047, -0.04322068, -0.04262783,
         0.03653221, -0.0384553 , -0.0366721 , -0.02913631,  0.04606477,
         0.04512571, -0.02018926,  0.06963478,  0.04972007, -0.0178906 ,
        -0.03832698,  0.06415725, -0.05555045, -0.01920224,  0.02573988,
         0.00577951, -0.06200162, -0.0680632 , -0.04091958, -0.03217451,
         0.01346954, -0.04848635, -0.05550119, -0.0226095 ,  0.04482557,
         0.03863275,  0.05660245, -0.02676181, -0.04413285, -0.04146598,
         0.06540901,  0.02507005, -0.01533917,  0.01642457, -0.04551997,
        -0.048147  ,  0.04590679,  0.04592167,  0.06853586,  0.0604962 ,
        -0.0269078 ,  0.04618484, -0.01478461, -0.00594246,  0.0143524 ,
        -0.02672207,  0.05269312, -0.07469476,  0.04135314,  0.04298363,
        -0.04770286,  0.04090019,  0.01234324, -0.05305671, -0.04117945,
         0.06915558, -0.04666137, -0.04370745,  0.02803757, -0.01323047,
        -0.03289756,  0.04684899,  0.04642456, -0.03885569,  0.04307263,
        -0.02202427, -0.03712534,  0.05504247, -0.02206683,  0.02234589,
        -0.02755387,  0.09415307, -0.04766554,  0.03745782,  0.03604499,
         0.01342538,  0.010289  , -0.01458033, -0.02481663, -0.04492195,
         0.03006232,  0.04820367,  0.03416118,  0.02659011, -0.05957802,
        -0.0208607 ,  0.03744152, -0.06476899, -0.03062152,  0.01145488,
        -0.02986346, -0.01362714, -0.06056589,  0.0108555 , -0.04692722,
        -0.05167743, -0.05045454,  0.03741269, -0.05079851, -0.0423258 ,
         0.01740641, -0.04717246, -0.04693799, -0.0590912 , -0.02076298,
        -0.06389542, -0.04018779, -0.02999884,  0.06194046,  0.03392199,
        -0.04976605, -0.05028386,  0.0471925 , -0.05599803, -0.0212184 ,
        -0.05262211,  0.03576803,  0.03680053, -0.0532264 , -0.07717989,
        -0.06154359, -0.04915591, -0.0577695 , -0.0291243 ,  0.04958079,
        -0.01867153,  0.04880437], dtype=float32),
 '000871c1fc726f0b': array([ 0.0595307 , -0.01182099, -0.07954371, -0.06524581,  0.03960848,
         0.10299347, -0.03958806,  0.07716946, -0.03807313, -0.04484146,
         0.0204614 ,  0.05589554,  0.08061892, -0.02916944,  0.0788346 ,
        -0.02437304,  0.06883342,  0.01899917,  0.04831464, -0.06213717,
        -0.03759369, -0.09170305,  0.04887071,  0.06112063,  0.044722  ,
        -0.06312192, -0.08967558,  0.03853054, -0.04474753, -0.01877869,
         0.06128575, -0.02923063, -0.10137064,  0.02927461, -0.0634903 ,
        -0.06895255,  0.0578188 ,  0.05369286,  0.09353667, -0.04989119,
         0.06271466,  0.05558071, -0.05837808,  0.04950204,  0.06971887,
        -0.03396401,  0.05761652, -0.02924585, -0.01230116, -0.02177357,
        -0.01725438, -0.00586518, -0.02299532, -0.03313383,  0.05965613,
         0.09829573, -0.02329416,  0.06042117,  0.02238701,  0.06883809,
         0.04473699, -0.0766469 ,  0.03106995,  0.07050055,  0.07481164,
         0.01969557, -0.05457015,  0.08354642,  0.06265053, -0.01485758,
        -0.04873144, -0.08222788,  0.03189747, -0.03803918,  0.03997781,
        -0.03006727, -0.02880614, -0.07245383, -0.02973753, -0.07674172,
         0.03039512,  0.06751957, -0.03720317, -0.04962572, -0.08670957,
         0.09432472,  0.04263216,  0.00821971, -0.01838481, -0.01957043,
        -0.01197593, -0.04190879,  0.08019501,  0.07072008, -0.06732979,
         0.05580782, -0.04673824, -0.01573396,  0.06200314, -0.06541193,
         0.0689595 , -0.04964249, -0.04292703, -0.02457828, -0.02634017,
        -0.07146057, -0.03533151, -0.04777947, -0.02438557,  0.0574894 ,
        -0.04099983,  0.01033456, -0.01717639,  0.08621539,  0.03131968,
        -0.03944671,  0.06479553,  0.05487191,  0.02325509, -0.06772356,
        -0.05661465,  0.01997088,  0.00914641,  0.05801944,  0.0721245 ,
        -0.07281413, -0.08036779, -0.03893352,  0.08120341,  0.04878327,
         0.06312788, -0.05090022, -0.06822246,  0.06956635,  0.05305036,
         0.07602683,  0.05090233, -0.01802053,  0.06405595,  0.04091335,
        -0.03974104,  0.04550684,  0.03482904, -0.03370424, -0.01563926,
         0.00864488,  0.08671006,  0.04974702, -0.04993182, -0.06404989,
        -0.02163973, -0.0739992 , -0.03974243,  0.02372676,  0.05156804,
        -0.07767509, -0.0713651 , -0.0908742 , -0.06506777,  0.08179977,
        -0.01538452,  0.02111884, -0.04604106,  0.03740237,  0.04571691,
        -0.02852873,  0.05947103,  0.07904235, -0.06762737,  0.05689915,
        -0.07357746,  0.03763729, -0.01290973, -0.04548074, -0.05208898,
         0.02209136, -0.05729776,  0.06419857,  0.07638715,  0.02129471,
         0.06763129,  0.03269514, -0.06218516, -0.01646772, -0.03930822,
         0.03794666, -0.01884049,  0.07406168,  0.0228627 , -0.068783  ,
         0.07395993,  0.05775927, -0.06488501, -0.06963488, -0.06153177,
        -0.00716947,  0.05098981, -0.03138823,  0.02289854, -0.0497626 ,
        -0.0411888 ,  0.06183695, -0.0718564 , -0.01850111,  0.04042202,
         0.05553921, -0.05457595, -0.04152023,  0.05750153,  0.03288958,
        -0.06982097, -0.06041235, -0.05125978, -0.03199292,  0.04594883,
         0.06627556,  0.07875931, -0.06839337,  0.01267225,  0.02212708,
        -0.0082586 ,  0.01325447, -0.04776989,  0.0360744 , -0.05083293,
         0.0139213 , -0.04374602, -0.04787344, -0.0338898 ,  0.05772957,
         0.05643763,  0.04549263,  0.03390848, -0.02226589, -0.04405053,
        -0.05347028,  0.05564523,  0.03786357,  0.03228492, -0.04177274,
         0.07199243,  0.01770389, -0.07256224,  0.05091802, -0.04266591,
         0.0686204 ,  0.04684334,  0.05341027,  0.02966318, -0.01616868,
         0.04706898,  0.04805208,  0.05076543,  0.0545285 ,  0.02756316,
        -0.04091481, -0.00328969, -0.02930789, -0.00725205,  0.0540034 ,
         0.04685501, -0.02749423, -0.01243833, -0.05084769, -0.0307192 ,
         0.03032592, -0.04851254,  0.04893808,  0.04837823,  0.03971462,
        -0.0355005 , -0.02696938,  0.03293609, -0.01451863,  0.04207433,
         0.04929565,  0.05502689,  0.02653845, -0.02411309,  0.01087799,
        -0.04784408,  0.03708264, -0.04364891, -0.04890688, -0.02082543,
        -0.05358465,  0.01679667, -0.00534076, -0.03637492, -0.04902072,
         0.04201821, -0.04711763,  0.0226139 ,  0.03128312, -0.02256848,
        -0.05437757,  0.03735593, -0.03166672, -0.03594834, -0.03332606,
        -0.04606759,  0.03529814, -0.03471679, -0.04266499,  0.01047258,
        -0.04933405, -0.03734203,  0.03023512, -0.02527826,  0.0141244 ,
        -0.02646709, -0.04292587,  0.01575907,  0.03553887, -0.04249746,
         0.00330273, -0.01500256,  0.02730677,  0.0182349 ,  0.02432301,
         0.02575524, -0.01219819, -0.01578352, -0.02767506,  0.03215653,
        -0.03921406, -0.04243146,  0.04002559, -0.03021883,  0.04166802,
         0.00477888, -0.03398769,  0.02756627,  0.02047571,  0.03364473,
        -0.02247125,  0.03976919, -0.04769712,  0.03737499, -0.02380298,
        -0.02527993, -0.05688684, -0.03784443, -0.0248084 , -0.03105644,
        -0.03532436, -0.0460795 , -0.0524088 ,  0.02296841,  0.02649232,
         0.02478555, -0.03220641, -0.04837628,  0.02292227, -0.03057679,
        -0.02530721, -0.04057522, -0.03182564, -0.02313889,  0.02810523,
        -0.02863751,  0.03384436, -0.0340447 ,  0.05332427, -0.02880006,
         0.00406971, -0.02323601, -0.0311776 ,  0.04800653,  0.02956968,
         0.02857499,  0.04265925,  0.03200955,  0.00441771,  0.03793799,
         0.0386872 ,  0.04407488,  0.03538385,  0.01171217, -0.02940144,
        -0.02136324,  0.03506843,  0.03966998,  0.03363995,  0.02850378,
        -0.05048965, -0.03385071, -0.04563338,  0.05876555,  0.03524269,
         0.00641925,  0.02607819,  0.03706773,  0.05356991,  0.00928238,
         0.03798328, -0.03643058,  0.02974436,  0.0606095 ,  0.03517095,
         0.05632128, -0.03008251,  0.04613126,  0.04996155, -0.00803877,
         0.02052315,  0.01927892,  0.04643289,  0.0190304 , -0.03026479,
         0.04644654, -0.01025858, -0.01978023,  0.04972481, -0.03492614,
         0.04308435,  0.03859767,  0.04711587,  0.01580227,  0.04379397,
        -0.01310633, -0.03366337,  0.01615378,  0.02653603,  0.04041102,
        -0.04801101, -0.03504028,  0.01310867, -0.03894357,  0.0160961 ,
         0.02451665, -0.03493308,  0.04459464,  0.02372236,  0.02068929,
         0.04481235, -0.00965101,  0.00882397, -0.01808648,  0.03422621,
        -0.01482868, -0.02815746,  0.04502134,  0.01878903, -0.02548482,
         0.04359414, -0.03536022,  0.00907566,  0.01774487, -0.01223962,
         0.04888519,  0.00549676,  0.03823575,  0.02666846,  0.00809151,
         0.02286969,  0.03908664,  0.02886889,  0.03955924,  0.02683911,
        -0.01944562,  0.02212713,  0.0550664 ,  0.02622687, -0.00702105,
        -0.00754664,  0.01154243,  0.03837648, -0.02884356, -0.0075181 ,
        -0.0144064 ,  0.00901427,  0.05599088,  0.03832353, -0.03999967,
        -0.03664615, -0.01678313,  0.05301841, -0.02377473, -0.02316814,
         0.02291992,  0.04219897,  0.05334336,  0.04250904,  0.03924156,
        -0.02087321,  0.05691009,  0.02701875, -0.04443198, -0.03239691,
         0.04102239,  0.04971036], dtype=float32),
 '00411460f7c92d21': array([ 0.09053408, -0.05417364, -0.08950792,  0.06667425, -0.08907049,
         0.0485078 , -0.03183122, -0.09230594, -0.05745179, -0.04953586,
         0.03760594,  0.06326323,  0.06356224,  0.03098915, -0.05211744,
        -0.03275352, -0.04185616, -0.0732556 , -0.03381157,  0.08374105,
         0.0761845 ,  0.02946974,  0.08020693,  0.05233693,  0.05142431,
        -0.0444577 , -0.07388331,  0.01459995,  0.07998186, -0.03849036,
         0.0687758 , -0.04503994,  0.05859865,  0.04295681,  0.06693538,
         0.02336338,  0.03375241, -0.03509335, -0.05819168,  0.07731059,
         0.0503627 , -0.06925051, -0.06274473,  0.06489848,  0.06171855,
         0.04040437,  0.0242433 , -0.0169816 , -0.05788652,  0.04264179,
        -0.03736158, -0.06103089,  0.0407596 ,  0.03015734, -0.04222763,
         0.08657327, -0.03303535,  0.04739821,  0.02236848, -0.06179685,
         0.06957415, -0.0440238 ,  0.04148097,  0.04661228, -0.04044539,
         0.0507602 , -0.026216  ,  0.01828547,  0.03793894, -0.0537768 ,
        -0.0440755 , -0.07389304, -0.05712048,  0.02117973, -0.02112797,
        -0.0687265 , -0.0538515 ,  0.02925348, -0.06408677,  0.06930401,
         0.04379052,  0.05624461, -0.06349775, -0.0524173 , -0.05502668,
         0.05139514,  0.03544733, -0.05584845, -0.04125142,  0.0716534 ,
        -0.06070136,  0.03537687, -0.07194112, -0.03546092, -0.02986979,
         0.01532627, -0.04458608,  0.0366087 , -0.03335092,  0.05471223,
        -0.02558496,  0.03386132, -0.04599739,  0.04263008,  0.04295464,
        -0.04453848,  0.05941341,  0.05655351,  0.03681397, -0.04585828,
         0.05325387,  0.07167184, -0.09161849, -0.072107  ,  0.07471055,
        -0.02407844, -0.02653542,  0.05049182, -0.02460504,  0.04050414,
        -0.06636041, -0.03964692,  0.0453622 ,  0.02410882, -0.04908845,
        -0.05423776,  0.04671949,  0.06364837, -0.06034956, -0.05766146,
        -0.06082786, -0.07355221,  0.03916111,  0.04081362,  0.0491659 ,
         0.07211321, -0.05382303, -0.05932818,  0.05713152,  0.07219474,
        -0.04763966,  0.05262964,  0.05135261,  0.02669947, -0.06806699,
         0.05224046,  0.06183203,  0.02158769,  0.04036364,  0.04857549,
        -0.0472701 ,  0.06480499, -0.04781689,  0.04344011, -0.06946652,
        -0.05065737, -0.06065474,  0.01836948, -0.02103627,  0.04979245,
         0.0200285 ,  0.00554187,  0.07086029,  0.05408689, -0.06699395,
        -0.08457021, -0.03870528,  0.06607879, -0.07315978, -0.05943829,
         0.02998064, -0.03647892,  0.00053718, -0.03969225,  0.02867691,
         0.04312984, -0.05632966,  0.01501217,  0.06090949, -0.03625473,
         0.05724896, -0.06138078, -0.03888431,  0.04965812, -0.04291908,
        -0.03076828, -0.0091822 ,  0.03390781, -0.02654145,  0.03765519,
         0.05665406,  0.03041126, -0.04884206,  0.04970706, -0.02549837,
        -0.04301127, -0.02765701,  0.05368855, -0.0699494 , -0.06926162,
         0.04921455, -0.05282259,  0.07410998,  0.0605079 ,  0.03283526,
         0.01188114, -0.03851649,  0.03459279,  0.02997885, -0.05252093,
        -0.04115303, -0.02551953,  0.06860658,  0.01774913,  0.07079697,
        -0.05037708,  0.05312676,  0.07575098, -0.04420511,  0.04676602,
         0.06808271, -0.03895267, -0.02489682, -0.0647001 ,  0.06123165,
        -0.0544643 ,  0.0354964 , -0.03275909, -0.06765722, -0.01588394,
         0.05614075,  0.07418992,  0.07825191,  0.07687686,  0.0294267 ,
        -0.09887318, -0.07477921,  0.06348902,  0.0388487 , -0.04216583,
         0.07458229,  0.02987958,  0.02164305,  0.04758062,  0.0324219 ,
         0.00321771,  0.06431612,  0.03461962,  0.06465621, -0.02285475,
         0.0350693 , -0.01774983,  0.02977098,  0.06027712,  0.02964835,
         0.01651759,  0.0150404 ,  0.0240381 ,  0.05184995, -0.041402  ,
         0.001323  , -0.01194209,  0.06323215,  0.03220835,  0.05594745,
         0.02315221, -0.01981462,  0.07474967,  0.04269074,  0.04334808,
         0.07199237, -0.04070745,  0.06001977,  0.06318431,  0.04346298,
         0.03573262,  0.03852824, -0.04712017,  0.06465138,  0.03942128,
         0.04396836,  0.04804841, -0.02656541,  0.02413101,  0.04053516,
         0.03855462,  0.01755116, -0.01186571, -0.02694165, -0.02199894,
        -0.01645295, -0.03327444,  0.04035205,  0.06196219,  0.05745242,
        -0.00619277, -0.02741608, -0.02900294,  0.04223251,  0.05101051,
         0.02943605,  0.0105442 ,  0.02598072,  0.03162096,  0.01646906,
         0.04042133, -0.05051379, -0.04750974,  0.0212409 ,  0.02063353,
        -0.05067313, -0.03805585,  0.04401473, -0.0566278 , -0.00180896,
        -0.02147643, -0.0325723 ,  0.02246759, -0.03917203, -0.04385308,
        -0.015503  ,  0.00438008, -0.03027432, -0.04156929,  0.02980387,
        -0.02214039,  0.02365579, -0.02461792, -0.02261942, -0.03804871,
        -0.05494965, -0.01100949, -0.04875296, -0.03392261, -0.04113407,
        -0.01877799, -0.04453559, -0.03684296,  0.03185675, -0.02317087,
        -0.04004918, -0.02449047,  0.02612101, -0.03790712, -0.01972761,
         0.04874967,  0.04247056, -0.04394875,  0.00336412, -0.02766513,
         0.01721239, -0.04902647,  0.03585602, -0.04520119, -0.04684522,
        -0.02418054, -0.03065841, -0.03141297,  0.01606166, -0.01394875,
        -0.02415047, -0.01749364, -0.0452022 , -0.0447638 , -0.03845756,
         0.02547652, -0.04324901, -0.04345585, -0.01366283,  0.06055094,
         0.05272457, -0.0127387 , -0.02757426,  0.01304375,  0.01869193,

In [2]:
import os
path = '../test_images/'
paths = [os.path.join(path, img) for img in os.listdir(path)]
os.listdir(path)

['d278df4919453195.jpg', '31784d9fc1fa0d25.jpg', '6cfe0e6127fa25df.jpg']

In [3]:
paths

['../test_images/d278df4919453195.jpg',
 '../test_images/31784d9fc1fa0d25.jpg',
 '../test_images/6cfe0e6127fa25df.jpg']

In [1]:
from wildlife_datasets import datasets, splits

ModuleNotFoundError: No module named 'wildlife_datasets'